version: 0.1.{build}
image: Visual Studio 2019
environment:
  DeployExtension: false
cache:
 - '%USERPROFILE%\.nuget\packages -> **\project.json'
configuration: Release
platform: Any CPU
build:
  project: src\ssdtProjectHelper.sln
artifacts:
  - path: src\projects\CommandDefinition\bin\$(configuration)